### ISSUE TITLE
Projects using latest Lime & latest HXCPP won't compile on iOS with XCode 12.1

### ISSUE THREAD

**Issue by valr2** [openfl/lime#1444]
I'm on macOS Catalina 10.15.7 with XCode 12.1, using Haxe 4.1.5, OpenFL 9.0.2 from haxelib and latest Lime taken from Github and compiled with `lime rebuild ios -clean`. I'm also using hxcpp 4.1.24, taken from http://nmehost.com/hxcpp/.

Making a simple HelloWorld OpenFL project and trying to build it in XCode, results in a `thread-local storage is not supported for the current target` compile error. Following the advice from https://github.com/HaxeFoundation/hxcpp/issues/937 I changed `-miphoneos-version-min=9.0` in iphoneos-toolchain.xml, part of hxcpp.

Now I get 6 other errors:
```
Undefined symbols for architecture arm64:
  "_UIKit_Vulkan_LoadLibrary", referenced from:
        _UIKit_CreateDevice in liblime.a(52b020b5_SDL_uikitvideo.o)
  "_UIKit_Vulkan_GetInstanceExtensions", referenced from:
      _UIKit_CreateDevice in liblime.a(52b020b5_SDL_uikitvideo.o)
  "_METAL_RenderDriver", referenced from:
      _render_drivers in liblime.a(0f76f2cb_SDL_render.o)
  "_UIKit_Vulkan_UnloadLibrary", referenced from:
      _UIKit_CreateDevice in liblime.a(52b020b5_SDL_uikitvideo.o)
  "_UIKit_Vulkan_CreateSurface", referenced from:
      _UIKit_CreateDevice in liblime.a(52b020b5_SDL_uikitvideo.o)
  "_UIKit_Vulkan_GetDrawableSize", referenced from:
      _UIKit_CreateDevice in liblime.a(52b020b5_SDL_uikitvideo.o)
ld: symbol(s) not found for architecture arm64
```

Seems some SDL-related problem? I tried adding various extra frameworks (e.g. Metal.framework) but it doesn't help.

If I use the official Lime 7.8.0 from haxelib instead, after fixing `-miphoneos-version-min=9.0` to get rid of the initial `thread-local storage is not supported for the current target` error, the app crashes because I don't have the `NSBluetoothAlwaysUsageDescription` key in my .plist file. After adding this key, the app runs fine on the device but asks for Bluetooth permission at startup, which is not what I want. According to https://github.com/haxelime/lime/issues/1429 I need to use the latest Lime from Github to get rid of that unwanted Bluetooth dependency, hence the 6 Vulkan/Metal errors above.

Any ideas on how to fix those Vulkan/Metal undefined symbols?
Thanks!

**Comment by pnkapadia64** [comment]
I'm getting
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_MTLSamplerDescriptor", referenced from:
      objc-class-ref in liblime.a(09027d115c01df8eeac9088e2042c6.o)
  "_OBJC_CLASS_$_MTLTextureDescriptor", referenced from:
      objc-class-ref in liblime.a(09027d115c01df8eeac9088e2042c6.o)
  "_OBJC_CLASS_$_MTLRenderPassDescriptor", referenced from:
      objc-class-ref in liblime.a(09027d115c01df8eeac9088e2042c6.o)
  "_OBJC_CLASS_$_MTLVertexDescriptor", referenced from:
      objc-class-ref in liblime.a(09027d115c01df8eeac9088e2042c6.o)
  "_OBJC_CLASS_$_MTLRenderPipelineDescriptor", referenced from:
      objc-class-ref in liblime.a(09027d115c01df8eeac9088e2042c6.o)
  "_MTLCreateSystemDefaultDevice", referenced from:
      _METAL_CreateRenderer in liblime.a(09027d115c01df8eeac9088e2042c6.o)
ld: symbol(s) not found for architecture arm64
```

I'm on macOS Catalina 10.15.7 with XCode 12.4
Lime Command-Line Tools (7.9.0)
Haxe Library Manager 4.0.2
Installed flixel version: 4.9.0

**Comment by superamadeus** [comment]
@pnkapadia64 I ran into the same issue and ended up here. 
Adding `<dependency name="Metal.framework" if="ios" />` to my `Project.xml` file fixed it for me.

**Comment by player-03** [comment]
Well this has been open a while.

It looks like adding the framework works for a lot of people, so I'm going to assume that either that or #1531 resolves the issue. Please feel free to correct me if not.

**Comment by joshtynjala** [comment]
Metal was added to Lime's Xcode project template for iOS in commit 216096270e6f84055787fefe83de8352fda771ec. It just hasn't been included in an official release yet.

**Comment by justin-espedal** [comment]
I just ran into the issue in the original post while attempting to build old versions of lime to reproduce a bug.

In `SDL_config_iphoneos.h`, there's the following line:
```cpp
/* Metal supported on 64-bit devices running iOS 8.0 and tvOS 9.0 and newer */
#if !TARGET_OS_SIMULATOR && !TARGET_CPU_ARM && ((__IPHONE_OS_VERSION_MIN_REQUIRED >= 80000) || (__TV_OS_VERSION_MIN_REQUIRED >= 90000))
#define SDL_PLATFORM_SUPPORTS_METAL	1
#endif
```

If that define is enabled, that will in turn enable `SDL_VIDEO_RENDER_METAL`, which will then include the unlinkable code mentioned in the first post. Setting the minimum ios version (`-miphoneos-version-min=9.0`) is what causes this.

Instead of adding the metal framework, I just set `SDL_PLATFORM_SUPPORTS_METAL` to stay 0 and it went back to compiling happily.

---

Given that lime doesn't support Metal (yet?), does the current SDL configuration actually give us anything, or is it just needlessly including some metal-related code and bloating binaries and our framework list? 🤔

**Comment by player-03** [comment]
> Given that lime doesn't support Metal (yet?)

I'd assume that enabling `SDL_PLATFORM_SUPPORTS_METAL` makes SDL use Metal for rendering, and so we do support Metal in that way.

If not, then leaving Metal out is probably better.
